### ISSUE TITLE
Facebook returning '\n'

### ISSUE THREAD

**Issue by CN91** [ArdaXi/Minilodon#14]
https://www.facebook.com/fail.nl/videos/1074946012552525/   

Zorgt er helaas voor dat ie crashed met de volgende error message

```
  File "/usr/local/lib/python3.5/site-packages/irc/client.py", line 905, in _prep_message
    raise InvalidCharacters(msg)
irc.client.InvalidCharacters: Carriage returns not allowed in privmsg(text)


```

Kennelijk een \n in de return ergens. Zit nog te bedenken hoe/wat/waar dit op te vangen is. 

Also reference voor error: 
https://github.com/jaraco/irc/blob/master/irc/client.py#L903

**Comment by CN91** [comment]
Nog een facebook - crasher 

```
Traceback (most recent call last):
  File "bot.py", line 2, in <module>
    bot.main()
  File "/home/ircd1/Minilodon/minilodon/bot.py", line 217, in main
    bot.start()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irc/bot.py", line 264, in start
    super(SingleServerIRCBot, self).start()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irc/client.py", line 1249, in start
    self.reactor.process_forever()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irc/client.py", line 278, in process_forever
    self.process_once(timeout)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irc/client.py", line 259, in process_once
    self.process_data(i)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irc/client.py", line 216, in process_data
    c.process_data()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irc/client.py", line 582, in process_data
    self._process_line(line)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irc/client.py", line 614, in _process_line
    handler(arguments, command, source, tags)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irc/client.py", line 646, in _handle_message
    self._handle_event(event)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irc/client.py", line 673, in _handle_event
    self.reactor._handle_event(self, event)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irc/client.py", line 398, in _handle_event
    result = handler.callback(connection, event)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/irc/client.py", line 1212, in _dispatcher
    method(connection, event)
  File "/home/ircd1/Minilodon/minilodon/minilodon.py", line 59, in on_pubmsg
    self.on_pubmsg_main(e)
  File "/home/ircd1/Minilodon/minilodon/minilodon.py", line 75, in on_pubmsg_main
    self.send_msg(result)
  File "/home/ircd1/Minilodon/minilodon/minilodon.py", line 254, in send_msg
    for line in msg:
  File "/home/ircd1/Minilodon/minilodon/bot.py", line 163, in on_message
    yield video(msg)
  File "/home/ircd1/Minilodon/minilodon/bot.py", line 180, in video
    return "[{0}] {1}{2}{3}".format(result['extractor_key'], result['title'],
KeyError: 'title'

```
